export class IConstants {
    public static ASK_ABDUL_EN = 'Ask Abdul';
    public static ASK_ABDUL_HIN = 'अब्दुल से पूछो';
    public static ASK_ABDUL_ARBIC = 'اسأل عبدال';
    public static ABDUL_THINKING_ARBIC = 'عبدال يفكر';
    public static ABDUL_THINKING_EN = 'Abdul is thinking';
    public static ABDUL_THINKING_HIN = 'अब्दुल सोच रहा है';
    public static ABDUL_NOT_AVAILABLE_HIN = 'फिलहाल अब्दुल उपलब्ध नहीं है। बाद में कोशिश करें';
    public static ABDUL_NOT_AVAILABLE_EN = 'Currently Abdul is not available. Please try later  Currently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try Currently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try laterCurrently Abdul is not available. Please try later';

}
